version: '3'
services:
  app:
    image: node:lts
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: 'sh -c "npm i && npm start"'
    ports:
      - 9090:9090
  server:
    image: node:lts
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: 'sh -c "npm i && npx pm2 --no-daemon start ecosystem-server.config.js"'
    ports:
      - 3030:3030
  console:
    image: node:lts
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: 'sh -c "npm i && npx pm2 start --no-daemon ecosystem-console.config.js"'
  output:
    image: node:lts
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: 'sh -c "npm i && npx pm2 --no-daemon start ecosystem-output.config.js"'